### ISSUE TITLE
Why Godot?

### ISSUE THREAD

**Issue by AlxTray** [WildTangent4/dune-generator#5]

**Comment by WildTangent4** [comment]
A few reasons

- Godot is free and open source, meaning no chance of a repeat of the unity incident
- From my experience it's less abstracted from the underlying systems than unity, meaning its easier to start programming without having to study the way the engine works
- The skills are fairly transferable as a lot of the rendering and mesh generation is just working almost directly with openGL
- I wanted to learn something new
